### ISSUE TITLE
YAMLException: unknown tag !<!reference>

### ISSUE THREAD

**Issue by RaphKa02** [studiometa/prettier-formatter-gitlab#50]
When I try to run
```
script:
  - npm ci
  - npx prettier-formatter-gitlab 'prettier -l .'
```
in my gitlab-ci.yml I get the following error:
```
file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:1273
  return new exception(message, mark);
         ^
YAMLException: unknown tag !<!reference> (10:45)
  7 |  ... 
  8 |  ... 
  9 |  ... 
 10 |  ... rence [.images, alpine, image]
-----------------------------------------^
 11 |  ... 
 12 |  ... 
    at generateError (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at composeNode (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2[61](https://gitlab.informatik.hs-augsburg.de/my-group/my-app/-/jobs/131241#L61)1:7)
    at readBlockMapping (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readDocument (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2[71](https://gitlab.informatik.hs-augsburg.de/my-group/my-app/-/jobs/131241#L71)5:3)
    at loadDocuments (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///builds/my-group/my-app/webtool/node_modules/js-yaml/dist/js-yaml.mjs:2804:19) {
  reason: 'unknown tag !<!reference>',
```

In my gitlab-ci.yml file I use the `!reference` syntax:
```yaml
webtool_format:
  image: !reference [.images, node, image]
  stage: lint
  variables:
    DIR: webtool
    ESLINT_CODE_QUALITY_REPORT: ./gl-codequality-format.json
  rules:
    - !reference [.default_rules, rules]
  script:
    - cd webtool/
    - npm ci
    - npx prettier-formatter-gitlab 'prettier -l .'
  artifacts:
    reports:
      codequality: ./webtool/gl-codequality-format.json
```

In `/eslint-formatter-gitlab/index.js` they address this issue in line 19
```js
/** @type {yaml.CollectionTag} */
const reference = {
  tag: '!reference',
  collection: 'seq',
  default: false,
  resolve() {
    // We only allow the syntax. We don’t actually resolve the reference.
  }
}
```
